// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	tools: {
		handy: {
			/**
			 * Handy Tools
			 */
			name: string
			/**
			 * Some handy tools, calculators, converters & generators
			 */
			description: string
			/**
			 * teenyicons:bulb-on-solid
			 */
			icon: string
			list: {
				bmicalculator: {
					/**
					 * Bmi Calculator
					 */
					name: string
					/**
					 * icon-park-solid:weight
					 */
					icon: string
					description: string
				}
				passwordgenerator: {
					/**
					 * Password Generator
					 */
					name: string
					/**
					 * material-symbols:password-rounded
					 */
					icon: string
					description: string
					l: {
						limitMsg: {
							/**
							 * Length
							 */
							str: string
							/**
							 * Characters
							 */
							unit: string
						}
					}
				}
				caseconverter: {
					/**
					 * Case Converter
					 */
					name: string
					/**
					 * fluent:convert-range-20-filled
					 */
					icon: string
					description: string
				}
				percentagecalculator: {
					/**
					 * Percentage Calculator
					 */
					name: string
					/**
					 * ant-design:percentage-outlined
					 */
					icon: string
					description: string
				}
				randomnum: {
					/**
					 * Random Number Generator
					 */
					name: string
					/**
					 * carbon:character-whole-number
					 */
					icon: string
					description: string
				}
				agecalculator: {
					/**
					 * Age Calculator
					 */
					name: string
					/**
					 * jam:birthday-cake-f
					 */
					icon: string
					description: string
				}
			}
		}
	}
}

export type TranslationFunctions = {
	tools: {
		handy: {
			/**
			 * Handy Tools
			 */
			name: () => LocalizedString
			/**
			 * Some handy tools, calculators, converters & generators
			 */
			description: () => LocalizedString
			/**
			 * teenyicons:bulb-on-solid
			 */
			icon: () => LocalizedString
			list: {
				bmicalculator: {
					/**
					 * Bmi Calculator
					 */
					name: () => LocalizedString
					/**
					 * icon-park-solid:weight
					 */
					icon: () => LocalizedString
					description: () => LocalizedString
				}
				passwordgenerator: {
					/**
					 * Password Generator
					 */
					name: () => LocalizedString
					/**
					 * material-symbols:password-rounded
					 */
					icon: () => LocalizedString
					description: () => LocalizedString
					l: {
						limitMsg: {
							/**
							 * Length
							 */
							str: () => LocalizedString
							/**
							 * Characters
							 */
							unit: () => LocalizedString
						}
					}
				}
				caseconverter: {
					/**
					 * Case Converter
					 */
					name: () => LocalizedString
					/**
					 * fluent:convert-range-20-filled
					 */
					icon: () => LocalizedString
					description: () => LocalizedString
				}
				percentagecalculator: {
					/**
					 * Percentage Calculator
					 */
					name: () => LocalizedString
					/**
					 * ant-design:percentage-outlined
					 */
					icon: () => LocalizedString
					description: () => LocalizedString
				}
				randomnum: {
					/**
					 * Random Number Generator
					 */
					name: () => LocalizedString
					/**
					 * carbon:character-whole-number
					 */
					icon: () => LocalizedString
					description: () => LocalizedString
				}
				agecalculator: {
					/**
					 * Age Calculator
					 */
					name: () => LocalizedString
					/**
					 * jam:birthday-cake-f
					 */
					icon: () => LocalizedString
					description: () => LocalizedString
				}
			}
		}
	}
}

export type Formatters = {}
